# Generated by Django 5.2 on 2025-04-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='customuser',
        #     name='address',
        # ),
        # migrations.RemoveField(
        #     model_name='customuser',
        #     name='company_name',
        # ),
        # migrations.RemoveField(
        #     model_name='customuser',
        #     name='location',
        # ),
        migrations.AddField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
