# Generated by Django 5.2 on 2025-06-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_file',
            field=models.FileField(blank=True, null=True, upload_to='id_files/'),
        ),
    ]
