# Generated by Django 5.2 on 2025-06-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_id_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_file',
            field=models.FileField(blank=True, null=True, upload_to='media/media/id_files'),
        ),
    ]
