# Generated by Django 5.2 on 2025-04-17 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MachinerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('business_permit', models.FileField(upload_to='media/business_permits')),
                ('epz_licence', models.FileField(upload_to='media/epz_licences')),
                ('kra_pin', models.CharField(max_length=50)),
                ('compliance_cert', models.FileField(upload_to='media/compliance')),
                ('lr_number', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.machinerysection')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sitc_code', models.CharField(max_length=50)),
                ('hts_code', models.CharField(max_length=50)),
                ('style_number', models.CharField(max_length=50)),
                ('fabric_content', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('production_quantity_per_month', models.IntegerField()),
                ('time_to_produce', models.DurationField()),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('fabric_source', models.CharField(blank=True, max_length=100, null=True)),
                ('accessories_source', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('office_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_order_type', models.CharField(max_length=100)),
                ('current_order_quantity', models.PositiveIntegerField()),
                ('expected_completion_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='application.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='application.companydetails')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.department')),
            ],
        ),
    ]
