# Generated by Django 5.2 on 2025-04-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Employee',
        ),
        migrations.RemoveField(
            model_name='companydetails',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='registration_cert',
            field=models.FileField(null=True, upload_to='media/registrations'),
        ),
    ]
