# Generated by Django 5.2 on 2025-04-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_employee_company_machinery_company_agoaapplication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
    ]
