# Generated by Django 5.2 on 2025-04-21 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_rename_category_productcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AlterModelOptions(
            name='agoaapplication',
            options={'verbose_name': 'AGOAApplication', 'verbose_name_plural': 'AGOAApplications'},
        ),
        migrations.AlterModelOptions(
            name='companydetails',
            options={'verbose_name': 'CompanyDetails', 'verbose_name_plural': 'CompanyDetails'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='machinery',
            options={'verbose_name': 'Machinery', 'verbose_name_plural': 'Machineries'},
        ),
        migrations.AlterModelOptions(
            name='machinerysection',
            options={'verbose_name': 'MachinerySection', 'verbose_name_plural': 'MachinerySections'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'ProductCategory', 'verbose_name_plural': 'ProductCategories'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='administrative_staff',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.CharField(choices=[('administrative', 'Administrative Staff'), ('cutting', 'Cutting'), ('production', 'Production'), ('finishing', 'Finishing'), ('sampling', 'Sampling')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cutting_assistants',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cutting_cutters',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cutting_helpers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cutting_spreaders',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cutting_supervisors',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='finishing_checkers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='finishing_final_inspector',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='finishing_helpers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='finishing_packing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='finishing_pressing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='finishing_stitchers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='finishing_supervisors',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='production_line_checkers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='production_packers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='production_stitchers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='production_supervisors',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sampling_pattern',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sampling_stitchers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sampling_supervisors',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
