# Generated by Django 5.2 on 2025-04-21 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='sampling_pattern',
            new_name='sampling_pattern_makers',
        ),
    ]
