# Generated by Django 5.2 on 2025-04-21 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_rename_sampling_pattern_employee_sampling_pattern_makers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='category',
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='application.companydetails'),
        ),
    ]
