# Generated by Django 5.2 on 2025-04-21 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_employee_category_alter_employee_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinery',
            name='section',
        ),
        migrations.AlterModelOptions(
            name='machinery',
            options={},
        ),
        migrations.RemoveField(
            model_name='machinery',
            name='number',
        ),
        migrations.RemoveField(
            model_name='machinery',
            name='type_name',
        ),
        migrations.AddField(
            model_name='machinery',
            name='air_compressors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='band_cutting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='bar_tack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='blind_stitch_hemming',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='button_attach',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='button_holing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='clocking_machines',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='collar_turners',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='computer_button_holing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='computer_welt_machine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='cutting_machines',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='double_needle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='edge_cutting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='electric_heated_dryers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='eyelet_button_holing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='fabric_inspector',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='fabric_notcher',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='feed_of_arms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='finishing_others_specify',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='machinery',
            name='fuel_pump',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='fusing_machines',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='generators',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='hydro_extractors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='industrial_washing_machine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='inhouse_clinic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machinery',
            name='iron_ordinary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='iron_steam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='manual_presser',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='overlock_3th',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='overlock_4th',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='overlock_5th',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='pattern_cutter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='sample_washers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='single_needle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='sn_computer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='snap_buttoning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='special_loops',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='steam_boilers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='steam_heated_dryers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='strapping_machines',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='thread_suckers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='thread_winders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='total_machines',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='waist_band_machines',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='water_feed_pump',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='weighing_scales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machinery_details', to='application.companydetails'),
        ),
        migrations.DeleteModel(
            name='MachinerySection',
        ),
    ]
