# Generated by Django 5.2 on 2025-04-21 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_remove_machinery_section_alter_machinery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinery',
            options={'verbose_name': 'Machinery', 'verbose_name_plural': 'Machinery'},
        ),
        migrations.RemoveField(
            model_name='machinery',
            name='finishing_others_specify',
        ),
    ]
