# Generated by Django 5.2 on 2025-04-21 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_agoaapplication_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='application.companydetails'),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machinery_details', to='application.companydetails'),
        ),
    ]
