# Generated by Django 5.2 on 2025-05-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_agoaapplication_certificate_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agoaapplication',
            name='certificate_file',
        ),
        migrations.AlterField(
            model_name='agoaapplication',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='application.companydetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='application.companydetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machinery',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machinery_details', to='application.companydetails'),
            preserve_default=False,
        ),
    ]
