# Generated by Django 5.2 on 2025-05-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_remove_agoaapplication_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agoaapplication',
            name='application_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
