# Generated by Django 5.2 on 2025-05-27 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_alter_employee_company_alter_machinery_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='application.companydetails'),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='machinery_details', to='application.companydetails'),
        ),
    ]
