# Generated by Django 5.2 on 2025-05-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_alter_employee_company_alter_machinery_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinery',
            name='total_machines',
        ),
    ]
