# Generated by Django 5.2 on 2025-05-29 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_remove_machinery_total_machines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agoaapplication',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='application.companydetails'),
        ),
    ]
