# Generated by Django 5.2 on 2025-06-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_alter_agoaapplication_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='agoaapplication',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
